CREATE DATABASE article;
USE article;

CREATE TABLE `article`.`posts` ( `Id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY, `Title` VARCHAR(200) NOT NULL , `Content` TEXT NOT NULL , `Category` VARCHAR(100) NOT NULL , `Created_date` TIMESTAMP NOT NULL , `Updated_date` TIMESTAMP NOT NULL , `Status` VARCHAR(100) NOT NULL ) ENGINE = InnoDB;